export const LATE_FEE_CENTS = 500;
export const LATE_FEE_WINDOW_HOURS = 24;
export const PREMIUM_DISCOUNT_PERCENT = 10;
export const STRIPE_MIN_AMOUNT_CENTS = 50;
export const CHECKOUT_SESSION_MINUTES = 31;
